# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy the HTML file into the Nginx directory
COPY index.html /usr/share/nginx/html/index.html

# Expose porti 8000 to the outside world
EXPOSE 8000

